---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secretstore-sm
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-sm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secretstore-sm
    kind: ClusterSecretStore
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.clusterSecretStore.secret }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-ps
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.region }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets-ps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-ps
    kind: SecretStore
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.secretStore.secret }}