apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tla-lrs
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tla-lrs
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    - repoURL: 'https://github.com/vgurukool/tla-helm'
      path: charts/tla-lrs/
      targetRevision: HEADß