apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tla-meetup
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cnoe
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tla-meetup
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://github.com/vgurukool/tla-helm'
      path: charts/indico/
      targetRevision: HEAD